# Setup
title:               Notes
tagline:             'Assorted technology items'
description:         ''
url:                 http://vadhri.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Vadhri
  url:               https://github.com/vadhri
  email:             saptarchi@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-178513523
